Proposal for Enhanced Graph Cloning in Apache Jena #2169:
apache/jena pull request #2316
Opened 2024-03-07 20:59 UTC by arne-bdt

GitHub issue resolved #2169

Pull request Description:
- added new interface Copyable<>
  - implemented Copyable#copy in GraphMem2 all three descendants (Legacy, Fast and Roaring)
  - extended TripleStore to implement Copyable<> and implemented it in all three descendants (Legacy, Fast and Roaring)
- added copy constructors to mem2/collections/*, mem2/store/*/*Bunch, mem2/store/*/*HashMap and mem2/store/*/*Set
- added unit tests to keep the test coverage for mem2/** at 100%
- added benchmark for GraphMem2#copy
- implemented new method G#copy which uses Copyable#copy if the graph implements it, otherwise G#copyGraphSrcToDst is used as fallback.
  - added a unit test for G#copy

----

 - [X] Tests are included.
 - [ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
 - [X] Commits have been squashed to remove intermediate development commit messages.
 - [X] Key commit messages start with the issue number (GH-xxxx, or if in JIRA, JENA-xxxx)

By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's Agreement](https://www.apache.org/licenses/contributor-agreements.html).

----

See the [Apache Jena "Contributing" guide](https://github.com/apache/jena/blob/main/CONTRIBUTING.md).

2024-03-10 13:35 UTC, afs requested changes
Looks great.

One request: Please change the commit message to 

"GH-2169: Enhanced GraphMem Cloning".

Starting with "issue number" is a pattern used to help when reading the commit history.

It looks ready to go to me so it is not a "Proposal" !

2024-03-10 13:44 UTC, namedgraph commented
What is the effect of this on applications using Jena?

2024-03-10 16:08 UTC, afs commented
> What is the effect of this on applications using Jena?

See the issue -- #2169.

If the application is using GraphMem's and it has need to copy graphs, then this is made faster.

2024-03-11 07:28 UTC, arne-bdt commented
> Looks great.
> 
> One request: Please change the first line of the commit message to
> 
> "[GH-2169](https://github.com/apache/jena/issues/2169): Enhanced GraphMem Cloning".
> 
> Starting with "issue number" is a pattern used to help when reading the commit history.
> 
> It looks ready to go to me so it is not a "Proposal" !

The commit message should be fixed now.

2024-03-11 08:16 UTC, afs approved these changes

2024-03-11 08:59 UTC, merged